# Generated by Django 2.1.7 on 2019-08-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20190827_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.FileField(upload_to='documents/')),
                ('aggregate', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='textJob',
        ),
    ]
