# Generated by Django 2.1.7 on 2019-08-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
